### ISSUE TITLE
Users created by admin persist between different installations

### ISSUE THREAD

**Issue by SinaMostafanejad** [molssi-seamm/seamm_dashboard#75]
## Version Details

- seamm-dashboard version: **2021.6.7.1**
- python version: **3.9**

## Problem:

- User created by admin in one installation persist in the dashboard and still shows up in a completely new installation. Meanwhile, the old password does not work anymore and has to be re-instated through admin again.

## Notes:

- The ~/SEAMM/* subfolders and conda environments are deleted between installations and browser's cache is deleted before running and reopening a new dashboard instance.

**Comment by janash** [comment]
@SinaMostafanejad - the user information is stored in the database file so users will show up in new install if you are using the same database. I'm not sure how this should be handled since it is part of the database. If you reinitialize the database (I believe there is a command line option of `--initialize` the users added previously will be removed.  The passwords should continue to work. Are you saying the users are persistent but their passwords are not?

**Comment by janash** [comment]
@paulsaxe is any of this relevant to your upcoming pull request with addressing #73 ?

**Comment by janash** [comment]
@SinaMostafanejad - I discussed with @paulsaxe a bit. If the issue is that you are seeing the user in the user list table, it's possible that this table is being improperly cached (which would be a different problem to fix). 

If you go to `api/users` when you are logged into the main account it should show the current users. Users should not carry over if the database is deleted if they were added manually.

**Comment by SinaMostafanejad** [comment]
Yes. In my case the users created in previous installations carry over to the new ones considering you have deleted everything in ~/SEAMM/*. The password for these users that have stayed does not work.

I have deleted whatever I could think of btw two installations, as explained. But this keeps happening. But as Paul was mentioning, this might be an innocuous problem for now because once you get it installed and working, there might not be a high probability for people to go right after deleting a working installation.

**Comment by janash** [comment]
Can you check `localhost:5000/api/users` while logged into the admin account? The users should not be stored if the database file is literally deleted. I cannot imagine how they would still be present if the database is gone because information about them is literally stored in the database file. If the database file is the same I would expect them to still be present in the dashboard. However, the password would also be expected to be the same. 

If they are still showing in the table it is possible that the table is cached, which would need to be fixed but is a different problem.

**Comment by janash** [comment]
Also, as a note. At this point, when jobs are added to the dashboard, the owner of the file is checked and a user is created if someone with that username does not exist in the dashboard. Do the files you're adding belong to different users, and are these the users which you are seeing in the users table? If so, I would completely expect the users to be created and the passwords to be reset when you reinitialize the dashboard.

**Comment by SinaMostafanejad** [comment]
I am closing this innocuous but annoying issue to see if anyone in the future would be bothered by it.
